In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import skfuzzy as fuzz

In [14]:
df_centrada = pd.read_csv("resultados_centrada.csv")
df_izq = pd.read_csv("resultados_izq.csv")
df_dcha = pd.read_csv("resultados_dcha.csv")

In [15]:
df_centrada['Dataset'] = 'Esfera centrada'
df_dcha['Dataset'] = 'Esfera derecha'
df_izq['Dataset'] = 'Esfera izquierda'

In [16]:
merged_df = pd.concat([df_centrada, df_dcha, df_izq], ignore_index=True)

In [17]:
print("Estadísticos: ")
print(merged_df.describe())

Estadísticos:
       Semilla Aleatoria  Número de Individuos  Número de Generaciones  \
count         288.000000            288.000000              288.000000
mean           45.000000              6.500000               12.500000
std            36.806302              1.502611                2.504352
min             0.000000              5.000000               10.000000
25%             0.000000              5.000000               10.000000
50%            45.000000              6.500000               12.500000
75%            90.000000              8.000000               15.000000
max            90.000000              8.000000               15.000000

       Tiempo de Simulación
count            288.000000
mean              14.438055
std                3.311667
min                7.400000
25%               12.450447
50%               13.620205
75%               15.110609
max               20.250500

In [18]:
merged_df.groupby(['Operador de Cruce']).describe()

                  Semilla Aleatoria                                         \
                              count  mean        std  min  25%   50%   75%
Operador de Cruce
1 punto                       144.0  45.0  36.870592  0.0  0.0  45.0  90.0
2 puntos                      144.0  45.0  36.870592  0.0  0.0  45.0  90.0

                        Número de Individuos       ... Número de Generaciones  \
                    max                count mean  ...                    75%
Operador de Cruce                                  ...
1 punto            90.0                144.0  6.5  ...                   15.0
2 puntos           90.0                144.0  6.5  ...                   15.0

                        Tiempo de Simulación                            \
                    max                count       mean       std  min
Operador de Cruce
1 punto            15.0                144.0  14.631487  3.231467  7.4
2 puntos           15.0                144.0  14.244623  3.390167  7.4


                         25%        50%        75%        max
Operador de Cruce
1 punto            12.814904  13.852768  15.125918  20.250500
2 puntos           12.015069  13.409236  14.884884  20.229885

[2 rows x 32 columns]

In [19]:
merged_df.groupby(['Operador de Mutación']).describe()

                     Semilla Aleatoria                                         \
                                 count  mean        std  min  25%   50%   75%
Operador de Mutación
Gaussiana                        144.0  45.0  36.870592  0.0  0.0  45.0  90.0
Uniforme                         144.0  45.0  36.870592  0.0  0.0  45.0  90.0

                           Número de Individuos       ...  \
                       max                count mean  ...
Operador de Mutación                                  ...
Gaussiana             90.0                144.0  6.5  ...
Uniforme              90.0                144.0  6.5  ...

                     Número de Generaciones       Tiempo de Simulación  \
                                        75%   max                count
Operador de Mutación
Gaussiana                              15.0  15.0                144.0
Uniforme                               15.0  15.0                144.0

                                                                     \
                          mean       std  min        25%        50%
Operador de Mutación
Gaussiana             13.39479  2.653736  7.4  11.837022  13.171468
Uniforme              15.48132  3.574440  7.4  13.114374  14.093347


                            75%       max
Operador de Mutación
Gaussiana             14.366069  20.19802
Uniforme              20.128834  20.25050

[2 rows x 32 columns]

In [20]:
merged_df.groupby(['Operador de Reemplazo']).describe()

                      Semilla Aleatoria                                   \
                                  count  mean        std  min  25%   50%
Operador de Reemplazo
Elitista                          144.0  45.0  36.870592  0.0  0.0  45.0
Generacional                      144.0  45.0  36.870592  0.0  0.0  45.0

                                  Número de Individuos       ...  \
                        75%   max                count mean  ...
Operador de Reemplazo                                        ...
Elitista               90.0  90.0                144.0  6.5  ...
Generacional           90.0  90.0                144.0  6.5  ...

                      Número de Generaciones       Tiempo de Simulación  \
                                         75%   max                count
Operador de Reemplazo
Elitista                                15.0  15.0                144.0
Generacional                            15.0  15.0                144.0

                                                                      \
                           mean       std  min        25%        50%
Operador de Reemplazo
Elitista               14.18079  3.365735  7.4  12.108374  13.444992
Generacional           14.69532  3.247999  7.4  12.677064  13.763424


                             75%        max
Operador de Reemplazo
Elitista               14.971548  20.250500
Generacional           15.118770  20.219781

[2 rows x 32 columns]

In [21]:
merged_df.groupby(['Semilla Aleatoria']).describe()

                  Número de Individuos                                     \
                                 count mean       std  min  25%  50%  75%
Semilla Aleatoria
0                                 96.0  6.5  1.507874  5.0  5.0  6.5  8.0
45                                96.0  6.5  1.507874  5.0  5.0  6.5  8.0
90                                96.0  6.5  1.507874  5.0  5.0  6.5  8.0

                       Número de Generaciones        ...              \
                   max                  count  mean  ...   75%   max
Semilla Aleatoria                                    ...
0                  8.0                   96.0  12.5  ...  15.0  15.0
45                 8.0                   96.0  12.5  ...  15.0  15.0
90                 8.0                   96.0  12.5  ...  15.0  15.0

                  Tiempo de Simulación                                       \
                                 count       mean       std  min        25%
Semilla Aleatoria
0                                 96.0  14.453141  3.522736  7.4  12.016804
45                                96.0  14.610196  3.197561  7.4  12.881143
90                                96.0  14.250828  3.229959  7.4  12.205175


                         50%        75%        max
Semilla Aleatoria
0                  13.721346  15.141133  20.250500
45                 13.480592  15.170563  20.229885
90                 13.667790  14.804331  20.219781

[3 rows x 24 columns]

In [22]:
merged_df.groupby(['Número de Individuos']).describe()

                     Semilla Aleatoria                                         \
                                 count  mean        std  min  25%   50%   75%
Número de Individuos
5                                144.0  45.0  36.870592  0.0  0.0  45.0  90.0
8                                144.0  45.0  36.870592  0.0  0.0  45.0  90.0

                           Número de Generaciones        ...              \
                       max                  count  mean  ...   75%   max
Número de Individuos                                     ...
5                     90.0                  144.0  12.5  ...  15.0  15.0
8                     90.0                  144.0  12.5  ...  15.0  15.0

                     Tiempo de Simulación                            \
                                    count       mean       std  min
Número de Individuos
5                                   144.0  14.611762  3.355146  7.4
8                                   144.0  14.264348  3.270044  7.4


                            25%        50%        75%        max
Número de Individuos
5                     12.698922  13.674091  15.415952  20.229885
8                     12.177258  13.480592  15.049254  20.250500

[2 rows x 24 columns]

In [23]:
merged_df.groupby(['Número de Generaciones']).describe()

                       Semilla Aleatoria                                   \
                                   count  mean        std  min  25%   50%
Número de Generaciones
10                                 144.0  45.0  36.870592  0.0  0.0  45.0
15                                 144.0  45.0  36.870592  0.0  0.0  45.0

                                   Número de Individuos       ...            \
                         75%   max                count mean  ...  75%  max
Número de Generaciones                                        ...
10                      90.0  90.0                144.0  6.5  ...  8.0  8.0
15                      90.0  90.0                144.0  6.5  ...  8.0  8.0

                       Tiempo de Simulación                            \
                                      count       mean       std  min
Número de Generaciones
10                                    144.0  14.300401  3.342027  7.4
15                                    144.0  14.575709  3.286892  7.4


                              25%        50%        75%        max
Número de Generaciones
10                      12.141705  13.486894  15.110609  20.229885
15                      12.677064  13.667790  15.129551  20.250500

[2 rows x 24 columns]